### PR TITLE
Assortativity

### PR DESCRIPTION
**Pull request by jpfairbanks**
Here are some updates. Each commit implements 1 change.
I normally make small changes in each commit and then rebase them before merging (or forget to rebase).

@akarpf, if you merge this (by clicking the merge button on the github site) or it will automatically update your PR to JuliaGraphs/Lightgraphs.jl.

### CODE REVIEW

**Comment by jpfairbanks** [comment]
The tests are in LightGraphs/test/centrality/assortativity.jl

They don't pass. I am pretty sure the CompleteGraph should have a positive and finite assortativity. double check the formulas and add more tests please.

**Comment by jpfairbanks** [comment]
You can run the tests locally by running Pkg.test("LightGraphs") at the julia prompt.

**Comment by akarpf** [comment]
@jpfairbanks I will be on vacation finally next week, then I will find the time. Sorry for the delay.

**Comment by akarpf** [comment]
@jpfairbanks Hi, So I am working on it. I found out that I didn't upload my latest version in January. One question: In order to make things comparable across different languages & libraries, wouldn't it make sense to integrate a standard example network into LG? I using the florentine marriages network in the test now. If you share this view, could you give me a hint how I can do this?

**Comment by jpfairbanks** [comment]
If you look at the datasets.jl file there are examples of small graphs that
we embed for tests. You can add a script to ./test/ that uses igraph or
networkx to compute the correct answers. Then you can run that script and
add the results to the test directory as well.

Dr. James Fairbanks
PhD CSE
Georgia Tech '16

**Pull request merged**
